const {
  VITE_APP_BASE_URL,
  VITE_APP_GOOGLE_MAP_API_KEY,
  VITE_APP_WEB_URL,
  VITE_APP_ENCRY_KEY,
  VITE_APP_TOKEN_LABEL,
  VITE_APP_REFRESH_TOKEN_LABEL,
  VITE_APP_FCM_TOKEN_LABEL,
  VITE_APP_USER_TOKEN_LABEL,
  VITE_APP_VAPID_KEY,
  VITE_APP_SOCKET_URL,
  VITE_APP_BOOKING_ADMIN_KEY,
  VITE_APP_BOOKING_URL,
} = import.meta.env;

export const API_URL = VITE_APP_BASE_URL;
export const BOOKING_URL = VITE_APP_BOOKING_URL;
export const SOCKET_URL = VITE_APP_SOCKET_URL;
export const WEB_URL = VITE_APP_WEB_URL;
export const GOOGLE_MAP_API_KEY = VITE_APP_GOOGLE_MAP_API_KEY;
export const ENCRYPTION_KEY = VITE_APP_ENCRY_KEY;
export const TOKEN_LABEL = VITE_APP_TOKEN_LABEL;
export const REFRESH_TOKEN_LABEL = VITE_APP_REFRESH_TOKEN_LABEL;
export const FCM_TOKEN_LABEL = VITE_APP_FCM_TOKEN_LABEL;
export const USER_TOKEN_LABEL = VITE_APP_USER_TOKEN_LABEL;
export const VAPID_KEY = VITE_APP_VAPID_KEY;
export const BOOKING_ADMIN_KEY = VITE_APP_BOOKING_ADMIN_KEY;
export const CHECK_BUSINESS_LABEL = "CHECK_BUSINESS_LABEL";
export const UNIQUE_DEVICE_ID = "UNIQUE_DEVICE_ID";
export const UNIQUE_DEVICE_MODEL = "UNIQUE_DEVICE_MODEL";
export const BUSINESS_LABEL = "BUSINESS_LABEL";
